#These params were in original file. Not sure if useful.
#recovery_behavior_enabled: false
#clearing_rotation_allowed: false
#simple_attractor: false

DWAPlannerROS: 
# Robot configuration parameters
  acc_lim_x: 0.5
  max_vel_x: 0.7
  min_vel_x: 0.0
  max_trans_vel: 0.7
  min_trans_vel: 0.3
  acc_lim_th: 1.0
  max_rot_vel: 1.5
  min_rot_vel: 1.0
  acc_lim_y: 0.0
  max_vel_y: 0.0
  min_vel_y: 0.0
# Goal tolerance parameters
  yaw_goal_tolerance: 1.0
  xy_goal_tolerance: 1.0
  latch_xy_goal_tolerance: true
# Forward simulation parameters
  sim_time: 3.0 # the durated of the planned path. Should be 2-4 s.
  sim_granularity: 0.025
  angular_sim_granularity: 0.1
  vx_samples: 10
  vy_samples: 0
  vth_samples: 20
  controller_frequency: 20.0 # default
# Trajectory scoring parameters
# cost =
#  path_distance_bias * (distance to path from the endpoint of the trajectory in meters)
#  + goal_distance_bias * (distance to local goal from the endpoint of the trajectory in meters)
#  + occdist_scale * (maximum obstacle cost along the trajectory in obstacle cost (0-254))
  path_distance_bias: 32.0
  goal_distance_bias: 24.0  
  occdist_scale: 0.01 
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.8
  max_scaling_factor: 0.2
  publish_cost_grid: true
# oscillation prevention parameters
  oscillation_reset_dist: 0.05
# Global plan parameters
  prune_plan: true
  meter_scoring: true


TrajectoryPlannerROS:
# Robot configuration parameters
   acc_lim_x: 0.5
   acc_lim_y: 0.0 # zero for a differential drive robot
   acc_lim_theta: 1.0
   max_vel_x: 0.6
   min_vel_x: 0.3
   max_vel_theta: 1.5
   min_vel_theta: -1.5
   max_vel_y: 0.0  # zero for a differential drive robot
   min_vel_y: 0.0
   min_in_place_vel_theta: 1.0
   escape_vel: -0.25   
   holonomic_robot: false
# Goal tolerance parameters
   yaw_goal_tolerance: 0.5 
   xy_goal_tolerance: 0.4  
   latch_xy_goal_tolerance: false
# Forward simulation parameters
   sim_time: 1.0
   sim_granularity: 0.025
   angular_sim_granularity: 0.025
   vx_samples: 20
   vy_samples: 0 # zero for a differential drive robot
   vtheta_samples: 20
   controller_frequency: 20.0
# Trajectory scoring parameters
   meter_scoring: true
   pdist_scale: 0.9
   gdist_scale: 0.6
   occdist_scale: 0.1
   heading_lookahead: 0.5
   heading_scoring: false
   heading_scoring_timestep: 0.8
   dwa: false
   publish_cost_grid_pc: false
   global_frame_id: map
# oscillation prevention parameters
   oscillation_reset_dist: 0.05
# Global plan parameters
   prune_plan: true

TebLocalPlannerROS:

 odom_topic: odom
 map_frame: /odom
    
 # Trajectory
  
 teb_autosize: True
 dt_ref: 0.3
 dt_hysteresis: 0.1
 global_plan_overwrite_orientation: True
 max_global_plan_lookahead_dist: 3.0
 feasibility_check_no_poses: 5
    
 # Robot
         
 max_vel_x: 0.4
 max_vel_x_backwards: 0.2
 max_vel_theta: 0.3
 acc_lim_x: 0.5
 acc_lim_theta: 0.5
 min_turning_radius: 0.0
 footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
   type: "point"
   radius: 0.2 # for type "circular"
   line_start: [-0.3, 0.0] # for type "line"
   line_end: [0.3, 0.0] # for type "line"
   front_offset: 0.2 # for type "two_circles"
   front_radius: 0.2 # for type "two_circles"
   rear_offset: 0.2 # for type "two_circles"
   rear_radius: 0.2 # for type "two_circles"
   vertices: [ [0.25, -0.05], [0.18, -0.05], [0.18, -0.18], [-0.19, -0.18], [-0.25, 0], [-0.19, 0.18], [0.18, 0.18], [0.18, 0.05], [0.25, 0.05] ] # for type "polygon"

 # GoalTolerance
    
 xy_goal_tolerance: 0.2
 yaw_goal_tolerance: 0.1
 free_goal_vel: False
    
 # Obstacles
    
 min_obstacle_dist: 0.4
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 1.0
 obstacle_poses_affected: 30
 costmap_converter_plugin: ""
 costmap_converter_spin_thread: True
 costmap_converter_rate: 5

 # Optimization
    
 no_inner_iterations: 5
 no_outer_iterations: 4
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.1
 weight_max_vel_x: 2
 weight_max_vel_theta: 1
 weight_acc_lim_x: 1
 weight_acc_lim_theta: 1
 weight_kinematics_nh: 1000
 weight_kinematics_forward_drive: 1
 weight_kinematics_turning_radius: 1
 weight_optimaltime: 1
 weight_obstacle: 50
 weight_dynamic_obstacle: 10 # not in use yet
 alternative_time_cost: False # not in use yet

 # Homotopy Class Planner

 enable_homotopy_class_planning: True
 enable_multithreading: True
 simple_exploration: False
 max_number_classes: 4
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_keypoint_offset: 0.1
 obstacle_heading_threshold: 0.45
 visualize_hc_graph: False

