v_max: 1.0
v_min: 0.1
v_max_neg: -1.0
v_threshold: 0.1

w_max: 1.5
w_min: 0.1
w_threshold: 0.1

acc_lim_x: 0.5
dec_lim_x: 0.5
acc_lim_theta: 1.0
dec_lim_theta: 1.0

base_width: 0.3

# footprint loaded as list of points, i.e. [x1, y1, x2, y2 ..]
footprint: [0.2, 0.2, 0.2, -0.2, -0.2, -0.2, -0.2, 0.2] 
# if radius is used instead of footprint
robot_radius: 0.4
