recovery_behaviors: [{
    name: conservative_reset, 
    type: clear_costmap_recovery/ClearCostmapRecovery
  }, {
    name: rotate_recovery1,
    type: rotate_recovery/RotateRecovery
  }, {
    name: aggressive_reset,
    type: clear_costmap_recovery/ClearCostmapRecovery
  }, {
    name: rotate_recovery2,
    type: rotate_recovery/RotateRecovery
  }]
  
planner_frequency:          0     # if zero, global plan updates on new goal or path blocked only
controller_frequency:       10
planner_patience:           5.0
controller_patience:        3.0
conservative_reset_dist:    2.0
recovery_behavior_enabled:  false # since we don't want the wheelchair to start making random movements.
clearing_rotation_allowed:  false
shutdown_costmaps:          false
oscillation_timeout:        0.0
oscillation_distance:       0.5
# max_planning_retries: 	    -1

# http://www.ros.org/wiki/navfn
NavfnROS:
  allow_unknown:                      true
  planner_window_x:                   0.0
  planner_window_y:                   0.0
  default_tolerance:                  0.1
  visualize_potential:                true
  planner_costmap_publish_frequency:  0.5

# http://www.ros.org/wiki/global_planner
GlobalPlanner:
   allow_unknown: false
   default_tolerance: 1.0
   visualize_potential: false
   use_dijkstra: true
   use_quadratic: true
   use_grid_path: false
   old_navfn_behavior: false
   lethal_cost: 253
   neutral_cost: 50
   cost_factor: 0.8
   publish_potential: true
   orientation_mode: 0
   orientation_window_size: 1
