active: true

use_scan: true
use_pcl: false
use_split_and_merge: true
circles_from_visibles: false
discard_converted_segments: false
transform_coordinates: true

#min_group_points: 5
max_group_distance: 0.1
#distance_proportion: 0.006
#max_split_distance: 0.2
#max_merge_separation: 0.2
#max_merge_spread: 0.2
#max_circle_radius: 0.5
#radius_enlargement: 0.0

frame_id: "base_footprint"
