# publishing frequency is same as incoming laserscan message
fixed_frame: odom
base_frame: base_footprint
use_imu: false
use_odom: true
use_vel: false #experimental, does not always improve the results. 

kf_dist_linear: 0.1
kf_dist_angular: 0.15

publish_tf: false
publish_pose: false
publish_pose_stamped: false
publish_odommsg: true

max_iterations: 10
max_correspondence_dist: 0.3
max_angular_correction: 0.45
max_linear_correction: 0.5

restart: 0
restart_threshold_mean_error: 0.01
restart_dt: 0.1
restart_dtheta: 0.1
clustering_threshold: 0.25
orientation_neighbourhood: 10
use_point_to_line_distance: 1
