active: true
publish_scan: true
publish_pcl: false
ranges_num: 1000

min_scanner_range: 0.15
max_scanner_range: 10.0


min_x_range: -10.0
max_x_range: 10.0
min_y_range: -10.0
max_y_range: 10.0

fixed_frame_id: "base_footprint"
target_frame_id: "base_footprint"


