odom_frame_id: odom
global_frame_id: map
base_frame_id: base_footprint
tf_broadcast: true

# AMCL model parameters
min_particles: 100
max_particles: 5000
kld_err: 0.01
kld_z: 0.99
update_min_d: 0.2 # Setting these update values to 0 means it will update at /scan rate
update_min_a: 0.3
resample_interval: 2
transform_tolerance: 0.2 # tolerance can be increased when computer gets too busy 
recovery_alpha_slow: 0.001 # advised: 0.001
recovery_alpha_fast: 0.1 #advised: 0.1

initial_pose_x: 0.0 # (double, default: 0.0 meters)
initial_pose_y: 0.0 # (double, default: 0.0 meters)
initial_pose_a: 0.0 # (double, default: 0.0 radians)
# initial_cov_xx (double, default: 0.5*0.5 meters)
# initial_cov_yy (double, default: 0.5*0.5 meters)
# initial_cov_aa (double, default: (π/12)*(π/12) radian)

# Map parameters
gui_publish_rate: 1.0
save_pose_rate: 0.5
use_map_topic: true
first_map_only: false

# Laser model parameters
laser_min_range: 0.15
laser_max_range: 10.0
laser_max_beams: 30 # default: -1.0. Setting this to default leads to shaking map for some reason. 

laser_z_hit: 0.95
laser_z_rand: 0.05

#laser_z_short: 0.1
#laser_z_max: 0.05

#laser_z_sigma_hit: 0.3
#laser_z_lambda_short: 0.1
#laser_likelihood_max_dist: 2.0
laser_model_type: likelihood_field
#laser_model_type: beam 
#angle_min: -3.0 # start angle of the scan [rad]
#angle_max: 3.0 # end angle of the scan [rad]
#angle_increment: 0.0 start angle of the scan [rad]
# time_increment (float32) time between measurements [seconds] - if your scanner is moving, this will be used in interpolating position of 3d points
# scan time time between scans [seconds]

# Odometry model parameters
odom_model_type: diff
odom_alpha1: 0.05
odom_alpha2: 0.05
odom_alpha3: 0.05
odom_alpha4: 0.05
