#These two params were in original file. Not sure if needed.
#recovery_behavior_enabled: false
#clearing_rotation_allowed: false

TrajectoryPlannerROS:
# Robot configuration parameters
   acc_lim_x: 1.5
   acc_lim_y: 0.0 # zero for a differential drive robot
   acc_lim_theta: 1.2
   max_vel_x: 0.5
   min_vel_x: 0.1
   max_vel_theta: 1.0
   min_vel_theta: -1.0
   max_vel_y: 0.0  # zero for a differential drive robot
   min_vel_y: 0.0
   min_in_place_vel_theta: 0.5
   escape_vel: -0.1
   holonomic_robot: false
# Goal tolerance parameters
   yaw_goal_tolerance: 0.2 # about 12 degrees
   xy_goal_tolerance: 0.2  # 20 cm
   latch_xy_goal_tolerance: false
# Forward simulation parameters
   sim_time: 1.0
   sim_granularity: 0.025
   angular_sim_granularity: 0.025
   vx_samples: 8
   vy_samples: 0 # zero for a differential drive robot
   vtheta_samples: 20
   controller_frequency: 20.0
# Trajectory scoring parameters
   meter_scoring: true
   pdist_scale: 0.9
   gdist_scale: 0.6
   occdist_scale: 0.1
   heading_lookahead: 0.325
   heading_scoring: false
   heading_scoring_timestep: 0.8
   dwa: true
   publish_cost_grid_pc: false
   global_frame_id: odom
# oscillation prevention parameters
   oscillation_reset_dist: 0.05
# Global plan parameters
   prune_plan: true

# Additional params found in original file
#   simple_attractor: false
