# goal definition
string doorway_request
---
# result definition
bool find_door
float32 point_x
float32 point_y
float32 point_z
float32 quat_x
float32 quat_y
float32 quat_z
float32 quat_w
---
# feedback
float32 percent